### ISSUE TITLE
OpenKeychain fails to recognize ASCII armor when lines exceed 64 chars

### ISSUE THREAD

**Issue by fabacab** [meitar/wp-pgp-encrypted-emails#11]
Weird issue, but seems like a solid bug report: https://wordpress.org/support/topic/ascii-armor-strings-compatibility-issue-with-openkeychain?replies=2#post-8212698

@DanielRuf, can you think of any reason why this would be a dangerous change to make? I can't and am thinking of rolling it into the next release to improve compatibility.

**Comment by DanielRuf** [comment]
64 should be ok, already using it here https://github.com/jasonhinkle/php-gpg/blob/dbdd6b22cd2e9a1181c291f84f9a4b7e479d7446/libs/GPG.php#L182

And they also use a width of 64 here https://hackage.haskell.org/package/openpgp-asciiarmor-0.1/docs/src/Codec-Encryption-OpenPGP-ASCIIArmor-Encode.html

Not 100% sure but at least the PEM RFC says each line should have 64 characters http://crypto.stackexchange.com/a/19055/12434

The default width for `wordwrap` is 75. http://php.net/manual/en/function.wordwrap.php

``` php
string wordwrap ( string $str [, int $width = 75 [, string $break = "\n" [, bool $cut = false ]]] )
```

Generally this should not make any problems and a width of 64 is expected in some PGP clients. Should be changed in the next release.

Oversaw that there was a width of 75 / the default value of wordwrap used.
