### ISSUE TITLE
Support S/MIME as a non-default option?

### ISSUE THREAD

**Issue by fabacab** [meitar/wp-pgp-encrypted-emails#13]
See https://wordpress.org/support/topic/accept-also-smime-keys/

**Comment by DanielRuf** [comment]
this should be possible using the OpenSSL functions of PHP
https://github.com/PHPMailer/PHPMailer/issues/127

For example http://php.net/manual/en/function.openssl-pkcs7-encrypt.php

**Comment by fabacab** [comment]
@DanielRuf @willhowells Would you be so kind as to help me test this implementation of S/MIME support? I have a few questions about the security of this implementation before I feel comfortable releasing it. The most pressing questions I have are:

1. How safe is [`openssl_pkcs7_encrypt()`](https://secure.php.net/openssl_pkcs7_encrypt)? Should I be using something else? I have attempted to understand its full implications by reading the PHP manual page and choosing the strongest cipher available. See [lines 83 through 86 of the current tip](https://github.com/meitar/wp-pgp-encrypted-emails/blob/83db7adab9b33597450126275fda3f279459c7db/includes/class-wp-smime.php#L83-L86).
1. Following on from that question, if there is no better tool, how can I most safely prevent sensitive data from remaining on disk? I have attempted to take extreme care of the filesystem by maintaining file handles and overwriting the data that was stored in those files with `random_bytes()` *before* I `unlink()`, but is there a better way? See [lines 93 to 99 of the current tip](https://github.com/meitar/wp-pgp-encrypted-emails/blob/83db7adab9b33597450126275fda3f279459c7db/includes/class-wp-smime.php#L93-L99).

Thanks again for your time and attention on this! :)

**Comment by DanielRuf** [comment]
Will answer later. So far overwriting before unlinking the file is a very good idea.

**Comment by DanielRuf** [comment]
Keep in mind that `random_bytes()` is just available natively on PHP 7+.

Not sure if OAEP is better but PKCS7 seems to be ok? I have to do some more research on this.

**Comment by fabacab** [comment]
> Keep in mind that `random_bytes()` is just available natively on PHP 7+.

Yeah, I know. But I'm [requiring WordPress 4.4](https://github.com/meitar/wp-pgp-encrypted-emails/blob/44e178d9af184ab182820cb7c027fd3a05f3384b/readme.txt#L5) or greater, which includes @ParagonIE's [`random_compat` project](https://github.com/paragonie/random_compat) out of the box, so I feel safe with that.

> Not sure if OAEP is better but PKCS7 seems to be ok? I have to do some more research on this.

[Optimal asymmetric encryption padding](https://en.wikipedia.org/wiki/Optimal_asymmetric_encryption_padding)? This is news to me. I will have to do some reading, too. Thank you for the feedback, looking forward to hearing about your own research as well!

**Comment by DanielRuf** [comment]
> Yeah, I know. But I'm requiring WordPress 4.4 or greater, which includes @paragonie's random_compat project out of the box, so I feel safe with that.

Ah my bad, forgot that it was included now :D

> Optimal asymmetric encryption padding? This is news to me. I will have to do some reading, too. Thank you for the feedback, looking forward to hearing about your own research as well!

Right. @paragonie use it in their projects and Scott also prefers this over the other PKCS standards as it seems because of oracle (padding) attacks (in PKCS1 1.5 and possibly others) which OAEP defeats if I did not misunderstand it.

**Comment by fabacab** [comment]
Oh, interesting. So, if I'm understanding this correctly, it looks like PHP's OpenSSL functions don't allow me to specify padding when using `openssl_pkcs7_encrypt()`, but I *can* specify specifically OAEP padding with [`openssl_public_encrypt()`](https://secure.php.net/manual/function.openssl-public-encrypt.php) (by passing the `OPENSSL_PKCS1_OAEP_PADDING` constant to the `$padding` parameter). However, I am not sure if this function will do what I need for S/MIME support? `openssl_pkcs7_encrypt()` seems to do a bunch of additional work to make sure the message is handled specifically as S/MIME. I assume I can do this work myself and then manually construct the MIME-formatted message with an encrypted message body using `openssl_public_encrypt()` if I have to, but that's a lot of stuff I don't totally understand yet and am not sure I have the time to do before the next release?

**Comment by DanielRuf** [comment]
You are totally right. Unfortunately I do not have enough time to test it myself if and how OAEP could be used for S/MIME. Best solution would be to release a first implementation with PKCS7 and then test some OAEP approach for better security to prevent (possible future) oracle padding attacks. After reading some more it seems PKCS1 (1.5) is problematic and OAEP is often recommended instead of this standard but PKCS7 should not have these issues?

**Comment by fabacab** [comment]
> Best solution would be to release a first implementation with PKCS7 and then test some OAEP approach for better security to prevent (possible future) oracle padding attacks.

This makes sense to me. This also will allow some time for early adopters from the WordPress ecosystem to test the rest of the S/MIME implementation. I have already encapsulated the encryption routines as a WordPress filter hook provided by this plugin (`smime_encrypt`) so any consumers should be isolated from encryption mechanism changes in future releases.

Thank you again for your time and for your generosity in pointing me towards the things I do not yet know or fully understand. :)

I'll close this issue as soon as I complete the merge from the `smime` topic branch into the `develop` branch later today.

**Comment by fabacab** [comment]
S/MIME support has been released in [version 0.6.0](https://github.com/fabacab/wp-pgp-encrypted-emails/releases/tag/0.6.0).

Many thanks to @willhowells for instigating the majority of this work and to @DanielRuf for your help briefly auditing the encryption implementation. :)

**Comment by fabacab** [comment]
To continue following S/MIME support, refer to issue #22.
