### ISSUE TITLE
Fatal error - Uncaught Error: Call to a member function setHash()

### ISSUE THREAD

**Issue by aalcaine** [meitar/wp-pgp-encrypted-emails#26]
We've installed your plugin, and everything is ok, we upload the private and public PGP keys, etc.,
but in some occasions (I think that when emails are sent to known people, because we've set that
option as is), appears an error message:

_Fatal error: Uncaught Error: Call to a member function setHash() on null in /var/.................../wp-content/plugins/wp-pgp-encrypted-emails/vendor/openpgp-php/openpgp_crypt_rsa.php:126 Stack trace: #0 /var/.................../wp-content/plugins/wp-pgpencrypted-emails/includes/class-wp-openphp.php(70): OpenPGP_Crypt_RSA->sign(Object(OpenPGP_LiteralDataPacket)) #1 /var/.................../ etc_, see attached file.
![errormsg](https://user-images.githubusercontent.com/32023824/30957031-501e41e8-a439-11e7-9c98-b5e8401e2196.png)

Any idea? :)

**Comment by fabacab** [comment]
No. The reason I don't know is that you said "on some occasions," which is very vague. Please read [How to write a good bug report](http://noverse.com/blog/2012/06/how-to-write-a-good-bug-report/) and then re-open this issue with more detail. Thanks.
