### ISSUE TITLE
ob_end_flush() failed

### ISSUE THREAD

**Issue by JosiahCarberry** [meitar/wp-pgp-encrypted-emails#35]
The following error message is logged after saving settings:

PHP message: PHP Notice: ob_end_flush(): failed to send buffer of zlib output compression (1) in /myhome/wp-includes/functions.php on line 3743, referer: https://mysite.com/wp-admin/options-general.php?page=wp-pgp-encrypted-emails 

What is more, the email sent is neither encrypted nor signed even though I have entered the public key for the admin address and have generated the key pair from within the plugin.

**Comment by fabacab** [comment]
Please supply useful information. I close issues that cannot be acted on. Consider reading [How to write a good bug report](http://www.noverse.com/blog/2012/06/how-to-write-a-good-bug-report/) if you are unsure what "useful information" means.
