### ISSUE TITLE
Protonmail support

### ISSUE THREAD

**Issue by enoch85** [meitar/wp-pgp-encrypted-emails#36]
Hi!

I read on Reddit that you made it possible to encrypt outgoing emails with Protonmail. Great stuff!

I'm running a webshop with Woocommerce and I want to encrypt all my outgoing messages. Right now I use WP-SMTP as Protonmail doesn't support SMTP for Wordpress, so I was wondering if this plugin will make it happen, and if so, how?

My end goal here is to send encrypted order confirmations to my users and at the same time send them my public key in the order email so that they are able to decrypt the message. Would that be possible?

**Comment by fabacab** [comment]
You should read less Reddit.

**Comment by enoch85** [comment]
@meitar Hmm: https://www.reddit.com/r/ProtonMail/comments/63k1i4/protonmail_with_wordpress_and_pgp/di4tw6n

**Comment by meitar** [comment]
Yup, that's probably all of what's in Reddit that's worth reading. :)

**Comment by meitar** [comment]
> could you please answer my questions?

@enoch85 No, I can't. Please stop interacting with my repo. If you do so again I will block you.

**Comment by enoch85** [comment]
@meitar Maybe you should stop being so  pompous and douchey.  Where's the care for other peoples friendly questions?

> If you do so again I will block you.

Please do, I will uninstall your app anyway after this conversation.
