### ISSUE TITLE
Admin access to other users' keys

### ISSUE THREAD

**Issue by sebastiencyr** [meitar/wp-pgp-encrypted-emails#37]
Hi,

I needed access to other users' pgp keys in their user profiles. 

I modified lines 151 and 152 to enable that as follows:

```php
add_action( 'plugins_loaded', function(){
    if( current_user_can('manage_options') ){
        add_action( 'edit_user_profile', array( __CLASS__, 'renderProfile' ) );
        add_action( 'edit_user_profile_update', array( __CLASS__, 'saveProfile' ) );
    }else{
        add_action( 'show_user_profile', array( __CLASS__, 'renderProfile' ) );
        add_action( 'personal_options_update', array( __CLASS__, 'saveProfile' ) );
    }
});
```

This would be useful in a future update I'm sure.

**Comment by fabacab** [comment]
Can you describe a use case in which a user should be allowed to modify the keys of another user? An admin already has access to the entire WordPress system, and changing *other users* PGP keys isn't something I'd like to make *too* easy, if you know what I mean. :)
