### ISSUE TITLE
ECC key not supported

### ISSUE THREAD

**Issue by Mikiya83** [meitar/wp-pgp-encrypted-emails#40]
Hi,
I use your plugin without problem with an OpenPGP RSA 4096bits key. But i just try to migrate to a new OpenPGP ECC key (X25519 type), and with this public key set in plugin setting for admin, my outgoing mails are not encrypted anymore.
Do you have any information about that ?
Thanks

**Comment by fabacab** [comment]
The upstream OpenPGP-PHP library does not yet support ECC keys. See singpolyma/openpgp-php#13 to track progress.
