### ISSUE TITLE
Can't encrypt text

### ISSUE THREAD

**Issue by BinaryAura** [meitar/wp-pgp-encrypted-emails#41]
After trying to encrypt text I get:
"Encryption of the text is not possible. Cannot read property 'toHex' of null" error.

All I'm doing here is trying to send my public key to another email user that may or may not be using mailvelope.

![image](https://user-images.githubusercontent.com/5960287/105090903-a9630380-5a64-11eb-9e0e-f5f0037de049.png)

**Comment by BinaryAura** [comment]
I'm using a Chromium browser on Fedora

**Comment by fabacab** [comment]
What you're experiencing has nothing to do with the WP PGP Encrypted Emails plugin whose issue tracker you are posting this in.
