### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by jason-weiser** [meitar/wp-pgp-encrypted-emails#44]
The curly braces in three files:

vendor/singpolyma/openpgp-php/lib/openpgp_crypt_symmetric.php (lines 125, 612, 628, 771, 1055 and more)
vendor/singpolyma/openpgp-php/lib/openpgp.php (line 218 and more)
vendor/singpolyma/openpgp-php/lib/openpgp_crypt_rsa.php (lines 65, 190 and more)

broke this plugin and produced a fatal PHP error (saying "Array and string offset access syntax with curly braces is no longer supported") on my site running PHP 7.4, breaking the site as well.

I went through and changed the  in the files on my install and the plugin worked, but the lines mentioned above are not an exhaustive list. I don't know how common this error is, but thought I should bring it to your attention.

**Comment by fabacab** [comment]
I don't understand what you're talking about because on the `main` branch, there is no line 612 [in the `vendor/singpolyma/openpgp-php/lib/openpgp_crypt_symmetric.php` file](https://github.com/fabacab/wp-pgp-encrypted-emails/blob/c275b1f04c6f927586721c28f70249837052f6db/vendor/singpolyma/openpgp-php/lib/openpgp_crypt_symmetric.php). No such line exists in the `develop` branch either. So, um, what?

**Comment by martifarm** [comment]
Hi, I have also received the following erro just now, after installing the plugin on php 8:
'PHP message: PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /var/www/html/wordpress/wp-content/plugins/wp-pgp-encrypted-emails/vendor/singpolyma/openpgp-php/lib/openpgp.php on line 125', referer:

**Comment by jason-weiser** [comment]
I apologize, lines 125, 612, 628, 771, 1055 were in the file vendor/singpolyma/openpgp-php/lib/openpgp.php

The vendor/singpolyma/openpgp-php/lib/openpgp_crypt_symmetric.php was a typo on my part.

Thanks for all your work on this! It's an awesome plugin.

**Comment by fabacab** [comment]
When I tested this on my own PHP 7.4 installation I saw a deprecation notice but not a fatal error. In any event, I've updated the plugin with the current experimental support for PHP 8.x versions, so this should no longer be a problem. You should be able to install version 0.8.0 of the plugin from the WordPress plugin directory now.
