### ISSUE TITLE
Send from address other than wordpress@...

### ISSUE THREAD

**Issue by VincentBentley** [meitar/wp-pgp-encrypted-emails#47]
I noticed that the generated keypairs are always for the wordpress user at the host's domain, E.g. wordpress@example.com

If the sender address for WordPress is changed using another plug-in, this plug-in's generated keypair does not use the new address, the keypair is always generated using 'wordpress@'. It would be nice to be able to use a different sender address other than wordpress@ like mailer@ or no-reply@ etc.

The plug-in's interface does not display what email ID has been encoded into the keypair. It was found by uploading the public key into a keyserver or examination with GnuPG.

Enhancements:
1. Display the email ID of the sender used that is encoded in the keypair
2. Lookup the current sender address before generating the keypair
3. Enable changing the WordPress sender email address for the system

**Comment by fabacab** [comment]
> Lookup the current sender address before generating the keypair

Is there a WordPress hook for this? If plugins filter the outgoing `From` header, there's no guarantee it will be readable at the time of key generation nor stable across the lifetime of the key. I'm not familiar enough with the current state of the API to know.

But either way, this all seems a little scope creep-y anyways. If you want to use another key, just generate the key using a different OpenPGP software tool and then paste it into the plugin's interface. That way you can use whatever key, with whatever user ID packets in it, that you want.

**Comment by VincentBentley** [comment]
Sadly, PHP is not a language I am expert in for me to submit a PR. I found a simple workaround that suits my situation. I edited the hardcoded email address on line 1127 of wp-pgp-encrypted-emails.php from:

`$from_email = 'wordpress@'.$sitename;`
to
`$from_email = 'admin@'.$sitename;`

**Comment by fabacab** [comment]
> If the sender address for WordPress is changed using another plug-in

Out of curiousity, what plug-ins do this? I've not encountered one. Again, the site's own sending email address is intentionally *not* supposed to be the same as the result of [the `get_bloginfo('admin_email')` function](https://developer.wordpress.org/reference/functions/get_bloginfo/) call because the former is *for the software* whereas the latter is *for the human administrator* identity. Due to the inherently vulnerable position of a WordPress Web site, the software's own PGP key is intentionally not supposed to be reused by the administrator(s) of the WordPress Web site software itself.

**Comment by VincentBentley** [comment]
I am using 'WP Change Email Sender' plugin
[https://wordpress.org/plugins/wp-change-email-sender/](url)

Initially, I wanted to use 'mailer@' for my website mailer's ID to have a distinction between automated emails and human sent email. My admin@ mail account was going to point to an inbound mail distribution group. Due to compatibility problems between all of the plugins I needed to use, I actually regret using WordPress for this project. But It has given me time to build a bespoke replacement.

**Comment by fabacab** [comment]
It looks like that entire plugin was written just to expose [this simple function](https://github.com/aminurislamarnob/wp-change-email-sender/blob/ea1a5e3e517c75807566d355136c732bec8b98b0/wp-change-email-sender.php#L104-L111) that sets a custom option and then uses [the `wp_mail_from` API hook](https://developer.wordpress.org/reference/hooks/wp_mail_from/) to modify the address. This plugin can easily be made compatible with that plugin by using the output of this filter as the value for any strings where this value is used.

I'm not sure I have time to actually refactor this plugin's code to do this but it's good to know that it should be a trivial patch for anyone with the interest to do it in the future.
