### ISSUE TITLE
Only Admin user has a text area for their public key

### ISSUE THREAD

**Issue by VincentBentley** [meitar/wp-pgp-encrypted-emails#48]
This could be a WordPress 5.8.3 issue or an incompatibility with 'Ultimate Member' plug-in. 
I looked at the code last night and saw a whitelist for Woo Commerce, does Ultimate Member need to be whitelisted too?

There is no 'Email Encryption' section in user profile pages. Only the Admin account has it.

Admin's profile
![AdminHasPGP](https://user-images.githubusercontent.com/52336293/148938105-17c8a8e4-3ae0-403d-910e-5c4a407462f9.png)

User (Subscriber role) profile
![SubscriberNoPGP](https://user-images.githubusercontent.com/52336293/148937169-1900dc4d-5a70-48e4-acf1-54d5ff0aa460.png)

**Comment by 13robin37** [comment]
You need to sign in with that user account to add the key. The field won't be visible for profiles other than the one you are logged in with.

**Comment by VincentBentley** [comment]
Ah that will explain it. I'm using Ultimate Member plug-in which overrides the standard forms. It has the ability to extend a user's profile and put those elements in a custom profile form. UM enables concealment of the standard WordPress interface, on my system only admin has access to the standard interface. Sadly, I have no idea how to get UM to access data specific to this plug-in, ie. the user's public key.

This can be closed. It is an incompatibility with a third party plug-in.
