### ISSUE TITLE
Syntax Error in 0.4.0

### ISSUE THREAD

**Issue by boblmartens** [meitar/wp-pgp-encrypted-emails#7]
OS: SUSE Enterprise Linux 11 SP 3
PHP: 5.3.x
WordPress: 4.4.2
Plugin Version: 0.4.0

I get this error in the logs:

`PHP Parse error:  syntax error, unexpected '[' in /srv/www/htdocs/wp-content/plugins/wp-pgp-encrypted-emails/class-wp-openpgp.php on line 70`

**Comment by boblmartens** [comment]
Thanks!

**Comment by fabacab** [comment]
Yeah, that was my mistake. I haven't quite finished setting up continuous integration for this but it's clearly past time that I do. :\
